import type { Game } from "@workspace/api-client-react";

// Static fallback — mirrors seed_games.py exactly (same ids, same order).
// Used when the API is unreachable so the UI always renders game cards.
export const STATIC_GAMES: Game[] = [
  {
    id: 1,
    title: "Numărătoare Veselă",
    description: "Numără de la 1 la 20, exersează par/impar și trasează cifrele cu degetul.",
    category: "matematica",
    ageMin: 3, ageMax: 7,
    imageUrl: "/games/game-matematica-1.png",
    isNew: true, isFeatured: true, requiresSubscription: false,
  },
  {
    id: 2,
    title: "Adunări Distractive",
    description: "Adunări, scăderi și primele tabele de înmulțire prin jocuri rapide.",
    category: "matematica",
    ageMin: 6, ageMax: 9,
    imageUrl: "/games/game-matematica-2.png",
    isNew: false, isFeatured: true, requiresSubscription: true,
  },
  {
    id: 3,
    title: "Alfabetul Vesel",
    description: "Învață literele alfabetului și sunetele lor prin asociere cu imagini.",
    category: "litere",
    ageMin: 3, ageMax: 7,
    imageUrl: "/games/game-litere-1.png",
    isNew: true, isFeatured: true, requiresSubscription: false,
  },
  {
    id: 4,
    title: "Lumea Dinozaurilor",
    description: "Descoperă dinozauri, numele și caracteristicile lor printr-o aventură interactivă.",
    category: "natura",
    ageMin: 4, ageMax: 8,
    imageUrl: "/games/game-natura-1.png",
    isNew: true, isFeatured: false, requiresSubscription: true,
  },
  {
    id: 5,
    title: "Forme și Culori",
    description: "Recunoaște forme geometrice, combină culori și trasează contururi.",
    category: "culori",
    ageMin: 3, ageMax: 7,
    imageUrl: "/games/game-culori-1.png",
    isNew: false, isFeatured: true, requiresSubscription: false,
  },
  {
    id: 6,
    title: "Lumea Animalelor",
    description: "Asociază animale cu sunetele, habitatele și puii lor.",
    category: "natura",
    ageMin: 3, ageMax: 7,
    imageUrl: "/games/game-natura-1.png",
    isNew: false, isFeatured: true, requiresSubscription: true,
  },
  {
    id: 7,
    title: "Ritmuri Vesele",
    description: "Reproduce secvențe muzicale simple apăsând pe instrumente colorate.",
    category: "muzica",
    ageMin: 4, ageMax: 8,
    imageUrl: "/games/game-muzica-1.png",
    isNew: true, isFeatured: false, requiresSubscription: true,
  },
  {
    id: 8,
    title: "Joc de Memorie",
    description: "Găsește perechile de cărți identice din 4 teme diferite — exersează memoria.",
    category: "memorie",
    ageMin: 4, ageMax: 9,
    imageUrl: "/games/game-memorie-1.png",
    isNew: true, isFeatured: false, requiresSubscription: true,
  },
  {
    id: 9,
    title: "Atelier de Desen",
    description: "Desenează liber sau colorează șabloane gata făcute, cu pensule și culori variate.",
    category: "creativitate",
    ageMin: 3, ageMax: 9,
    imageUrl: "/games/game-creativitate-1.png",
    isNew: false, isFeatured: false, requiresSubscription: true,
  },
  {
    id: 10,
    title: "Puzzle de Logică",
    description: "Rezolvă puzzle-uri de logică, sortare și asociere la mai multe niveluri.",
    category: "logica",
    ageMin: 5, ageMax: 9,
    imageUrl: "/games/game-logica-1.png",
    isNew: false, isFeatured: false, requiresSubscription: true,
  },
  {
    id: 11,
    title: "Labirint",
    description: "Navighează prin labirint cu 3 niveluri de dificultate și 5 teme: animale, fructe, legume, obiecte, spațiu.",
    category: "labirint",
    ageMin: 4, ageMax: 9,
    imageUrl: "",
    isNew: true, isFeatured: true, requiresSubscription: true,
  },
  {
    id: 12,
    title: "Caută Cuvinte",
    description: "Găsește cuvinte ascunse în grilă! 5 categorii: animale, fructe, legume, obiecte, spațiu.",
    category: "cuvinte",
    ageMin: 5, ageMax: 9,
    imageUrl: "",
    isNew: true, isFeatured: true, requiresSubscription: true,
  },
  {
    id: 13,
    title: "Unește Punctele",
    description: "Conectează punctele în ordine și desenează imagini amuzante!",
    category: "creativitate",
    ageMin: 3, ageMax: 7,
    imageUrl: "",
    isNew: true, isFeatured: true, requiresSubscription: true,
  },
  {
    id: 14,
    title: "Zip Zap",
    description: "Conectează punctele numerotate în ordine și umple toată grila! 60 de niveluri cu dificultate crescătoare.",
    category: "logica",
    ageMin: 5, ageMax: 10,
    imageUrl: "",
    isNew: true, isFeatured: true, requiresSubscription: true,
  },
  {
    id: 15,
    title: "Petice",
    description: "Acoperă toată grila cu petice dreptunghiulare! Fiecare petic trebuie să respecte numărul și forma din indiciu.",
    category: "logica",
    ageMin: 5, ageMax: 10,
    imageUrl: "",
    isNew: true, isFeatured: true, requiresSubscription: true,
  },
];
